baseURL = "https://joundy.dev/"
languageCode = "en-us"
title = "Joundy's Blog"
theme = "PaperMod"
robotsNoIndex = true

[params]
defaultTheme = 'dark'
disableThemeToggle = true

[params.homeInfoParams]
WithCircle3D = false
Name = "Joundy Syafie"
Title = "Software Engineer"
# ImageUrl = "/images/profile.png"
ResumeUrl = "/resume"
ResumeText = "Resume"

Content = """
- ### Hello
-
- I'm from Banjarnegara, a small and scenic city in Indonesia, and I'm 25 years old. I'm really passionate about technology, especially in software engineering.
- 
- I work as a Software Engineer speciailized in backend development, and infrastructure, and I'm skilled in Rust, Golang, and Javascript/Typescript.
-
- For the past 3 years, I've been working in the blockchain space. I helped build NFT marketplaces on Near Protocol (paras.id) and Bitcoin Ordinals (ordzaar.com). Recently, I've also been working on Bitcoin Layer 2 projects called East Layer and Glittr Protocol.
- 
- Besides my technical skills, I'm good at working with different teams. I have experience working at startups where I helped develop large-scale applications used by people around the world.
"""

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/joundy"

[[params.socialIcons]]
name = "github"
url = "https://github.com/joundy"
