baseURL = "https://joundy.me/"
languageCode = "en-us"
title = "Jon's Site"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Hafiz Joundy Syafie"
Content = """
- ### Welcome to **Jon's Site**
-
- Hello, my name is [**Hafiz Joundy Syafie**](https://www.linkedin.com/in/joundy/), I was born in **Banjarnegara** **22** years ago, it's a small and beautiful city in **Indonesia**, I  really love anything about technology, especially in the programming world.
-
- I have been learning to code since I was in high school, I remember the first project that I made, it was the “Hello World” program, I didn’t expect a simple project that contains 11 characters had brought me to the programming realm and ended as a **Software Engineer**.
-
- I'm a Software Engineer that focuses on the Backend side, so far I have 3 main proficient programming languages: [**Javascript**](https://nodejs.org/), [**Golang**](https://go.dev/), and [**Rust**](https://www.rust-lang.org/)
-
- I have experience working in startup companies, developing large-scale applications to handle end-users across the world, besides the technical skills I also have soft skills for collaborating between teams like the Product team and QA.
-
- Currently, I'm working at [Paras Digital](https://paras.id), the biggest **NFT Marketplace** in **NEAR Protocol**, trust me it's a really cool company with amazing teams :D
"""
ImageUrl = "/images/profile.jfif"
ResumeUrl = "/resume"
ResumeText = "Jon's Resume"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/joundy"

[[params.socialIcons]]
name = "github"
url = "https://github.com/joundy"
