baseURL = "https://joundy.me/"
languageCode = "en-us"
title = "Jon's Blog"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Hafiz Joundy Syafie"
Content = """
- ### Welcome to **Jon's Blog**
-
- Hello, my name is [**Hafiz Joundy Syafie**](https://www.linkedin.com/in/joundy/), I was born in **Banjarnegara** **22** years ago, it's a small city in **Indonesia**, I  really love anything about technology, especially in the programing world.
-
- I started learning program when I was in high school, I remember when I was coding vbasic lang for the first time, the "Hello World" project, the project that will change my life forever and ended as a **Software Engineer**.
-
- I'm a Software Engineer that focuses on the Backend side, for now, I have 3 main proficient languages:
- [**Javascript**](https://nodejs.org/), [**Golang**](https://go.dev/), [**Rust**](https://www.rust-lang.org/)
-
- Currently, I'm working at [Paras Digital](https://paras.id), the biggest **NFT Marketplace** in **NEAR Protocol**, trust me it's a really cool company with amazing teams :D
"""
ImageUrl = "/images/profile.jfif"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/joundy"

[[params.socialIcons]]
name = "github"
url = "https://github.com/joundy"
