baseURL = "https://joundy.me/"
languageCode = "en-us"
title = "Jon's Blog"
theme = "PaperMod"
robotsNoIndex = true

[params]
defaultTheme = 'dark'
disableThemeToggle = true

[params.homeInfoParams]
WithCircle3D = false
Name = "Hafiz Joundy Syafie"
Title = "Software Engineer"
# ImageUrl = "/images/profile.png"
# ResumeUrl = "/resume"
# ResumeText = "Resume"

Content = """
- ### Hello
-
- I was born in **Banjarnegara**, **23** years ago, it's a small and scenic city in **Indonesia**. I am very passionate about technology, particularly programming.
-
- I am a Software Engineer who specializes in the **Backend**, currently proficient in **Javascript**, **Golang**, and **Rust**.
-
- As well as my technical skills, I have soft skills for collaborating between teams. I have worked in startups developing large-scale applications for users worldwide.
-
- I'm currently working for [Ordzaar](https://ordzaar.com), **NFT marketplace** in the **Bitcoin Ordinal Protocol**, ex: **Paras Digital**, **Ruangguru**, **Telkom Indonesia**.
-
- **contact@joundy.me**
"""

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/joundy"

[[params.socialIcons]]
name = "github"
url = "https://github.com/joundy"
